services:
  db:
    image: mariadb:10.9.2
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080