name: Deploy Develop
on:
  push:
    branches:
      - 'develop'
jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: Miwoli OVH VPS

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
            
      - name: Install dependencies
        run: npm ci && npm run bootstrap
    
      - name: Build
        run: npm run build:develop

      - name: 'Prepare dist'
        run: |
          mkdir ../build
          cp -r ./packages/cms/ ../build/cms
          cp -r ./packages/frontend/dist/frontend ../build/frontend
          tar -czvf build.tar.gz ../build/

      - name: 'Deploy'
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.ADDRESS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: 'build.tar.gz'
          target: '/var/www/jugger/${{ secrets.DEVELOP_URL }}'

      - name: 'Execute remote'
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.ADDRESS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          script: |
            cd /var/www/jugger/${{ secrets.DEVELOP_URL }}
            tar -xzvf build.tar.gz
            cp /var/www/jugger/${{ secrets.DEVELOP_URL }}/develop.env /var/www/jugger/${{ secrets.DEVELOP_URL }}/build/cms/.env
            cd build/cms
            npm ci
            pm2 restart jugger_cms_dev